### ISSUE TITLE
Twitter Widget Width trick to find

### ISSUE THREAD

**Issue by ronanguilloux** [OpenWines/openwines.github.io#3]
solutions : 
- https://www.geekgoddess.com/change-twitter-widget-to-wider-than-520px/
- http://stackoverflow.com/questions/12539496/html-css-for-twitter-widget-width

Proposal:

``` css
#twitter-widget-0 { 
    width: 100% !important; 
}
```
